on: [push,pull_request]

jobs:
  main_job:
    runs-on: ubuntu-latest
    name: Hardhat Unit Testing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install
      - run: npx hardhat --config dev_hardhat.config.js test test/contract_tests.js
