#on: [push] Silence it until slither fixes the bug.
on:
  push:
    branches:
      - non-exist

jobs:
  main_job:
    runs-on: ubuntu-latest
    name: static code analysis 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Slither Static Analysis
        uses: luisfontes19/slither-static-analysis-action@v0.3.2
        with:
          slither-version: '0.8.2'
          slither-params: '--solc-remaps @openzeppelin=node_modules/@openzeppelin'
          run-npm-install: true
          high-threshold: 1
          medium-threshold: 1
          low-threshold: 1
          optimization-threshold: 1
          informative-threshold: 10
          projectPath: "contracts"
